#!/usr/bin/env groovy
pipeline{
    agent any

    //Define stages for the build process
    stages{
        //Define the deploy stage
        stage('Deploy'){
            steps{
                //The Jenkins Declarative Pipeline does not provide functionality to deploy to a private
                //Docker registry. In order to deploy to the HDAP Docker registry we must write a custom Groovy
                //script using the Jenkins Scripting Pipeline. This is done by placing Groovy code with in a "script"
                //element. The script below registers the HDAP Docker registry with the Docker instance used by
                //the Jenkins Pipeline, builds a Docker image of the project, and pushes it to the registry.
                script{
                    docker.withRegistry('https://build.hdap.gatech.edu'){
                        // Build AAMobile docker image.
                        // Run the docker container to build the APK (Android executable)
                        // Copy the APK output onto the static content folder of the webservice below.
                        
                        // Build the AAWebserivce image--including the APK as a static content.
                        // def webserviceImage = docker.build("aa-api:latest", "-f AAMobile/Dockerfile .")
                        def webserviceImage = docker.build("aa-api:latest", "-f ./AAWebServices/Dockerfile ./AAWebServices")
                        // Push into HDAP's docker registry.
                        webserviceImage.push('latest')
                    }
                }
            }
        }

        //Define stage to notify rancher
        stage('Notify'){
            steps{
                script{
                    rancher confirm: true, credentialId: 'rancher-server', endpoint: 'https://rancher.hdap.gatech.edu/v2-beta', environmentId: '1a7', environments: '', image: 'build.hdap.gatech.edu/aa-api:latest', ports: '', service: 'AAA/api', timeout: 60
                    rancher confirm: true, credentialId: 'rancher-server', endpoint: 'https://rancher.hdap.gatech.edu/v2-beta', environmentId: '1a7', environments: '', image: 'redislabs/rejson:latest', ports: '', service: 'AAA/redis', timeout: 60
                }
            }
        }
    }
}
